### ISSUE TITLE
Trelby does not export special characters correctly to PDF

### ISSUE THREAD

**Issue by maccagnan** [limburgher/trelby#21]
When exporting to PDF (regardless of the font chosen) Trelby does not export special characters (such as Öìíàáòóèé etc.) correctly.
This happens regardless of whether the characters are imported from text or generated by Trelby's characters map.

**Comment by janopae** [comment]
In the original Trelby repository, at one point, most issues seem to have been removed. Before that, there was a very old issue about special character support in Trelby: https://web.archive.org/web/20201226153814/https://github.com/oskusalerma/trelby/issues/85

Reading the discussion, it seems that Trelby used to at least support the [Latin 1 charset](https://en.wikipedia.org/wiki/ISO/IEC_8859-1), which at least Ö, é and è should be part of.

However, in the discussion it gets obvious that embedding special characters to PDFs seems to be complicated. In the discussion, someone raises the idea of not creating the PDF "by hand" in Trelby, but rather use a library for this, that handles all the nitty-gritty details (like special character treatment). To that, then-maintainer oskusalerma replies that these libraries also couldn't solve the issue (as generating PDFs with abritary Unicode characters and abritary fonts was an unsolvable issue), to which another user replies that this is BS.

I agree that this is BS, as I have a little bit of experience with Apache FOP, which works using arbitrary unicode characters with abritary fonts.

I think we should look into replacing the hand generating of PDFs with a library.

~The current code uses a self-invented "Page Modeling Language" (PML) to abstract rendering documents, that can then be rendered to PDF, Postscript etc. (with the known limitations). Maybe, we could get rid of this invention completely by using a library.~ The "Page Modeling Language" is not only the model for PDF and Postscript, but also for rendering the document on screen. It has nothing to do with this issue, it is basically the core of Trelby (next to its file format), and I don't think we will or should replace it (maybe rename it).

There is an integration for Apache FOP into Python: https://pypi.org/project/pypfop/

But it bundles Java (because Apache FOP is written in Java), and this might be a bit huge for a dependency. Also, I'm not sure if Apache FOP supports any other API than FO, which is their declatative XML format for writing PDFs. This XML format is great for creating PDFs with a fixed layout and changing contents, but as there is a lot the user can configure about the layout in Trelby, I'm not sure if this would get in our way at some points. Also, this would be very different from the way our current PML works, which has an imperative API, directly accessible from Python (with no XML in between).

The Reportlab Toolkit is another very popular solution for creating PDFs in Python: https://pypi.org/project/reportlab/

It is written directly in Python, which should be much more lightweight than bundling Java. And it's made by a company that has specialised in PDF generation: https://www.reportlab.com/

The module itself uses a Python API, which is much closer to what we do with PML than using a declarative XML. But in case we need it, they also provide an additional module that parses declarative XML files and generates PDFs from them.

If we manage to port our PDF rendering code to a library like this, we're going to get rid of a lot of poorly documented and hardly tested source code. Bugs within that source code (like special characters not being supported) would vanish. I think we should give it a try.

**Comment by maccagnan** [comment]
@janopae Sounds great.

**Comment by janopae** [comment]
> Reading the discussion, it seems that Trelby used to at least support the [Latin 1 charset](https://en.wikipedia.org/wiki/ISO/IEC_8859-1), which at least Ö, é and è should be part of.

This can be confirmed by downloading the Trelby binary from the website, which still supports characters like these. The reason why Trelby stopped supporting non-ASCII Latin1 characters is the change from Python 2 to Python 3: Python originally encoded characters in Latin1 and now encodes them with UTF-8. For ASCII characters, that doesn't make a difference because both, Latin1 and UTF-8, are based on ASCII. Only non-ASCII Latin1 characters are encoded wrong this way. I landed a quick fix which resolves this issue.

A remaining issue is supporting non-Latin1 characters (e. g. Russian, Japanese or other writing systems not based on the Latin one), like reported in https://web.archive.org/web/20201226153814/https://github.com/oskusalerma/trelby/issues/85. This could indeed be resolved by using the reportlab library, which is a work which is ongoing in #59. I'll make a new issue for this.
