### ISSUE TITLE
Compare scripts does not seem to function.

### ISSUE THREAD

**Issue by maccagnan** [limburgher/trelby#51]
Trelby 2.4.7
Devuan Chimaera
Evince

Compare scripts does not seem to function. It does not create a PDF file and does not display any error.

Here is the terminal output:

$ trelby

(trelby:2485): dbind-WARNING **: 09:26:06.796: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
09:26:06: Debug: Adding duplicate image handler for 'PNG file'
Traceback (most recent call last):
  File "/usr/share/trelby/src/trelby.py", line 2511, in OnCompareScripts
    self.panel.ctrl.OnCompareScripts()
  File "/usr/share/trelby/src/trelby.py", line 740, in OnCompareScripts
    sp2 = copy.deepcopy(sp2)
  File "/usr/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
TypeError: __deepcopy__() takes 1 positional argument but 2 were given

**Comment by Cerabbite** [comment]
This is only the problem when having "Use same configuration" toggled on. If toggled of it does generate a PDF with the difference.

The problem seems to be in Pythons copy module, but I have yet to figure out why exactly this error exists, and possibly for how long this error has been here. Because this line has not been changed since 2005 https://github.com/limburgher/trelby/commit/777ede12

**Comment by Cerabbite** [comment]
To try and debug this issue I made a copy of the copy module and pasted in the src folder. So I can make changes. This is my [pr](https://github.com/Cerabbite/trelby/tree/fix-bug-%2351-deepcopy-error) to follow my progress


The bug was not there, in the last official released version (2.2)
I think something went wrong when porting from Python 2 to Python 3, because this issue has been here since the first release in this repo.

**Comment by Cerabbite** [comment]
@limburgher Any ideas on how to port deepcopy to Python 3? Or do you think it is another problem?

**Comment by limburgher** [comment]
No, what's odd is in the Screenplay class they talk about implementing their own deepcopy for performance reasons but it uses copy.deepcopy.

**Comment by maccagnan** [comment]
Confirm disabling "Use same configuration" works.

**Comment by limburgher** [comment]
Fixed it. https://github.com/limburgher/trelby/pull/53

**Comment by Cerabbite** [comment]
Indeed works perfectly now
