### ISSUE TITLE
Installation update breaks deb packages

### ISSUE THREAD

**Issue by limburgher** [limburgher/trelby#82]
When I build an RPM from 2.4.9, it works just fine. When I submit a build to OBS to make Ubuntu and Debian packages, the path in bin/trelby is incorrect.

Should be : sys.path.insert(0, "/usr/share/trelby/src")
Is: sys.path.insert(0, "/usr/share/trelby//usr/share/trelby//usr/share/trelby/src")

This appears to be a result of 9f3edf62b5b3cabc2f7e871288872daacc8db590.

Since distutils is removed in Python 3.12, I was planning on completely modernizing the installation system anyway, but if you know of a quick fix for this, we can do that in the interim.

**Comment by limburgher** [comment]
@janopae

**Comment by janopae** [comment]
Hm, it I assume `modify_import_path_in_trelby_bin` gets called multiple times, and always replaces a part of the string – first, it changes `insert(0, "src")` to `insert(0, "/usr/share/trelby/src")`, then it changes `insert(0, "/usr/share/trelby/src")` to `insert(0, "/usr/share/trelby//usr/share/trelby/src")`, then it changes `insert(0, "/usr/share/trelby//usr/share/trelby/src")` to `insert(0, "/usr/share/trelby//usr/share/trelby//usr/share/trelby/src")`.

I have no overview which distutils command has which subcommands, probably, there are multiple `easy_install` commands chained or something else. I'd need to do some complicated debugging to find out what actually goes wrong.

But a quick fix could be to use a bigger string for doing the replacement. E. g., instead of matching `src`, we could match `"src"`, which should be sufficient to prevent multiple replacements from having an effect in almost all imaginable cases already.

**Comment by limburgher** [comment]
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!
