### ISSUE TITLE
can't change PDF fonts

### ISSUE THREAD

**Issue by maccagnan** [limburgher/trelby#9]
I copied the courier10fonts both to /usr/share/fonts and /usr/trelby/resources, then selected them from the menu script > settings > change > PDF/fonts.
After selecting the cour10p_r.ttf fonts, it won't OK the selection and only export to the standard fonts..

**Comment by limburgher** [comment]
I've managed to get fonts to import and render a PDF, but the text is invisible.
https://github.com/limburgher/trelby/tree/issue-9

**Comment by maccagnan** [comment]
Invisible? Maybe the script was written with lemon juice. Have you tried heating the screeen?

**Comment by limburgher** [comment]
Sadly my last Pentium 4 is no more.

Good news though, one of the original upstream maintainers will be taking a look.

**Comment by maccagnan** [comment]
Pentium 4 was a glorious machine.
Hope he can find the problem. I haven't found any other issues so far. Export to txt and fountain is fine.

**Comment by limburgher** [comment]
If there's a ttf font file that you can always successfully use in PDF exports in Trelby 2.2, can you email me a copy? I'm doing some experimenting and I want to make sure I'm starting from something that works.

**Comment by maccagnan** [comment]
These are the courier 10 fonts I always used to export PDF's in 2.2 and 2.3 without any problem.
They can also be downloaded from trelby.org

**Comment by limburgher** [comment]
I just pushed some cleanup to the issue-9 branch. I see that if I add some print statements at src/truetype.py at line 64, version and tableCnt are coming back different that expected for cour10p_r.ttf. I'm not sure why these contants are set the way they are.

**Comment by maccagnan** [comment]
I have no idea too. What I find curious is that there isn't an error when exporting the PDF, but that Trelby refuses to save the settings altogether right from the menu window, when any kind of fonts are selected. The good news is I have written two drafts with 2.4 so far and no other issues have arised.

**Comment by rcentros** [comment]
Thanks for updating Trelby. Up until now, 2.3 has worked fine on both my Linux Mint machines and Debian (in Chromebook — which still uses Buster, but I upgraded it to Bullseye). Bullseye won't support or install Trelby 2.3 so, even though I can drop back for now, I will eventually have to use 2.4.x, which does install. But I've got the same issue with PDF fonts in the Chromebook and in Linux Mint 20.1). In 2.3 I can set Courier Screenplay (available from FadeInPro's website for download) just by linking to its location (for each font). Since I use Courier Screenplay both for Display and printing, it's really nice (much darker than the standard Courier font). Trelby 2.4.3 won't let me use it. It won't even try to save it in the PDF Font Menu. If I load a preset template (which already includes the Courier Screenplay Font family) it will not print to PDF — it won't even try. If I try Export to PDF it will give me "Save" dialog, will act like it's working, but it doesn't save anything. If I blank all PDF font information in the PDF font Menu — it all works, but prints to standard Courier. So, for some reason, Trelby 2.4.x is not reading in external fonts. It's like the method to link the external font is broken. (Sorry for the long post.) Trelby is still my favorite screenplay application, been using it since 2012. (Even beta tested the original Blyte in (I believe) 2004.)

**EDIT:** **I've found a work-around that changes the PDF font** (at least for Courier Screenplay -- which is what I use). Apparently the issue is in Trelby trying to read in the font file. If you already have the font installed in your system (I do have Courier Screenplay installed), then you leave the File: section blank. Just put the name of the font in the correct slot, don't even add the .ttf extension. (So, in my case, uner **Normal:** CourierScreenplay, under **Bold:** Courier-Screenplay-Bold, under **Italic:** CourierScreenplay-Italic and under **Bold Italic:** CourierScreenplay-BoldItalic) and it will work correctly. But it won't let you save this in your sconf file. (You have to edit that by hand.) My main .sconf file is LetterBold.sconf (Letter size paper with Bold Headers). To edit this .sconf file to work with Trelby 2.4.x, I just go to the bottom of the file and remove the longer font lines that have "filename:" in them. So back to normal with Trelby on Bullseye. Very happy, should be able to use Trelby for several more years now. (This works both in Linux Mint and on the Chromebooks.)

**EDIT 2:** So far no luck with Courier Prime. **EDIT 3:** Kind of a "like, duh" moment. Just had to rename the Courier Prime font (the font itself) by putting hyphens in the open spaces to get it to work.

**Comment by limburgher** [comment]
@rcentros I can confirm that this workaround works with every font I've tried on Trelby 2.4.3 on Fedora 34.
@maccagnan Can you try this? This is exciting. :)

**Comment by maccagnan** [comment]
@rcentros 
@limburgher 

Confirmed, it works for me on Devuan Chimaera and Debian Testing.
This is a life saver while the issue is fixed otherwise.
Thanks a lot!

**Comment by janopae** [comment]
Setting a font name and no file doesn't include the font in the PDF file. On systems that don't have the selected font installed, this will break the PDF (unless you select one of the few [standard PDF fonts](https://kbpdfstudio.qoppa.com/standard-14-pdf-fonts/) required by the PDF standard to be present in every reader). I think that's not what you really want to achieve with a PDF, and I guess it's more of a bug that this is even possible.
